---
- apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - build-essential
    - git
    - libxml2-dev
    - libxslt1-dev
    - python-dev
    - python-pip

- synchronize: src=~/Development/taas dest=~/ delete=yes perms=yes
               recursive=yes

- pip: name={{ item }} state=latest
  with_items:
    - argh
    - argcomplete
    - jinja2
    - nose
    - python-keystoneclient
